// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shithcisneycijdwpntw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaXRoY2lzbmV5Y2lqZHdwbnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjM5NzAsImV4cCI6MjA2MDIzOTk3MH0.QD613NlNbPY4V3jh81ituzCVLHUy8G-QVhPn-n0xy9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);